version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - db-data:/data/db/recipe-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recipe-db

  app:
    image: teamjeffry/receptboken:latest
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS: password
      DB_DATABASE: recipe-db
      DB_HOST: mongo
    depends_on:
      - mongo

volumes:
  db-data:
    driver: local